// Generated by https://quicktype.io

import { Category } from "./Categories";

export interface Products {
    total: number;
    productos: Producto[];
}

export interface Producto {
    precio: number;
    _id: string;
    nombre: string;
    categoria: Category;
    usuario: Category;
    img?: string;
}

